stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - src/logger/__init__.py
      - src/connections/s3_connection.py
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_transformation:
    cmd: python src/data/data_transformation.py
    deps:
      - src/data/data_transformation.py
      - data/raw/train.csv
      - data/raw/test.csv
      - references/feature_store.yaml
    outs:
      - data/interim/train_transformed.csv
      - data/interim/test_transformed.csv
      - models/preprocessor/preprocessing_pipeline.pkl

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/interim/train_transformed.csv
      - data/interim/test_transformed.csv
      - references/feature_store.yaml
    outs:
      - data/processed/train_balanced.csv
      - data/processed/test_processed.csv

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/processed/train_balanced.csv
    outs:
      - models/model/model.cbm

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - data/processed/test_processed.csv
      - models/model/model.cbm
    outs:
      - reports/model_evaluation_info.json
      - reports/figures/confusion_matrix.png
      - reports/figures/precision_recall_curve.png
      - reports/figures/prediction_distribution.png
      - reports/figures/roc_curve.png
    metrics:
      - reports/evaluation_metrics.json

  register_model:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - reports/model_evaluation_info.json
      - models/model/model.cbm